"""
Provider System - Base Interface
"""
from abc import ABC, abstractmethod
from typing import Any, List, Optional
from pydantic import BaseModel, Field

class ProviderMessage(BaseModel):
    """Represents a standardized message to be sent to an AI Provider."""
    role: str = Field(..., description="The role of the message sender (e.g., 'user', 'system', 'assistant').")
    content: str = Field(..., description="The text content of the message.")

class ProviderResponse(BaseModel):
    """Represents a standardized response received from an AI Provider."""
    content: str = Field(..., description="The textual response generated by the AI.")
    raw_response: Any = Field(None, description="The raw response object returned by the provider SDK for debugging.")
    model_used: Optional[str] = Field(None, description="The specific model used for this completion.")

class Provider(ABC):
    """Abstract Base Class for all AI Providers."""
    
    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Returns the unique identifier for this provider (e.g., 'groq', 'openai')."""
        pass
        
    @abstractmethod
    def initialize(self) -> None:
        """
        Initializes the provider, loading credentials from the environment.
        Raises an exception if required credentials are missing.
        """
        pass
        
    @abstractmethod
    def send_prompt(self, messages: List[ProviderMessage], model: Optional[str] = None, **kwargs) -> ProviderResponse:
        """
        Sends a conversation to the AI and returns the response.
        
        Args:
            messages: A list of ProviderMessage objects.
            model: Optional model name to override the default.
            **kwargs: Additional parameters (e.g., temperature).
            
        Returns:
            ProviderResponse containing the AI's reply.
        """
        pass
        
    @abstractmethod
    def health_check(self) -> bool:
        """
        Validates if the provider is currently available and authenticated.
        
        Returns:
            True if the provider is healthy, False otherwise.
        """
        pass
